# Generated by Django 3.2.8 on 2021-12-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalSociety_APP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master',
        ),
    ]
