# Generated by Django 3.2.8 on 2021-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalSociety_APP', '0005_auto_20211203_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='Mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
